### ISSUE TITLE
Создать jsp веб приложение из maven archetype 

### ISSUE THREAD

**Issue by tsogto** [mipractice/ramin_project#3]

**Comment by chrpnv** [comment]
@tsogto @RaminR

**Comment by chrpnv** [comment]
не стал пушить сюда. запушил сюда: github.com/chrpnv/jsp

**Comment by chrpnv** [comment]
не работает. не могу понять в чем ошибка. почему то jsp не видит то, что ему сервлет отправляет

**Comment by chrpnv** [comment]
решил проблемы, вот рабочий: https://github.com/chrpnv/jsp1
