### ISSUE TITLE
Переделать имена пакетов

### ISSUE THREAD

**Issue by tsogto** [mipractice/ramin_project#5]
Надо убрать использование rr и ramin в пакетах, так это не только ваш личный проект.
Используем общий пакет ru.esstu.se  
должна быть такая структура пакетов (это про модуль CRUD)
ru.esstu.se.dao  интерфейсы и реализации дао 
ru.esstu.se.service  интерфейсы и реализации сервисов
ru.esstu.se.model

**Comment by RamaObama** [comment]
Я внес изменения в проект.
